ameba-color-palette.css

- Black @10% for background
- Light Yellow for notification background

Add some colors.

---

package-lock.json
package.json

stylelint: `^7.11.1` to `^8.2.0`
stylelint-config-standard: `^16.0.0` to `^17.0.0`

Upgrade dev dependencies.

---

ameba-color-palette.css

Updated the doc:
https://company-84672.frontify.com/document/151334#/basics/colors

add: ameba news theme color.

---

.github/workflows/test.yml
.travis.yml
README.md

GitHub Actionsでtestを毎回実行するようにしました（もともとTravis-CIが入っていたのに変える必要があったのか🤔?）。

Add test workflow

---

ameba-color-palette.css

- カラーパレットの値にアップデートがあったので更新
- 現状のColor登録名に合わせてproperties名を微修正
- object, border colorの追加
- focus時の色指定に用いるシステムカラーを追加
```
--color-focus-clarity: var(--focus-blue-100);
--color-focus-ambiguous: var(--focus-blue-30-alpha);
```

feat(design system): update color palette

---

ameba-color-palette.css
package.json

Expressive colorsをSwatch colorとして追加しました。
※ 移行を目的としてしばらくの間、v3とv4を並行して運用していきます。v3への変更は `v3` ブランチへ向けていきます。

feat: add expressive colors

---

ameba-color-palette.css

いくつかの色定義を追加・修正

---

ameba-color-palette.css

いくつかの色定義を追加・修正 

---

ameba-color-palette.css

ハイライトカラーに黄色が追加されました。
ref: https://spindle.ameba.design/57edc1abc/p/118eaf-ui-color/b/89e8f0/t/826f45
こちらもExpressive Colorsと同様に試しにv4だけの追加にしてみます。

feat: add highlight yellow

---

ameba-color-palette.css

サードパーティカラーを2つ追加しました。
close #41

feat: add Apple and YouTube colors

---

ameba-color-palette.css

`Surface Secondary` の指定が間違っていたので修正しました。

fix: use alpha color as surface secondary

---

ameba-color-palette.css

feat: add --color-border-strong-emphasis

---

ameba-color-palette.css

feat: add `color-system-black`

---

ameba-color-palette.css

Toast & SnackBarのinformationで使用するカラーを追加しました

feat: add surface accent neutral

---

.github/workflows/test.yml

ci: some improvements

---

.github/workflows/release.yml
.github/workflows/test.yml

#96 でテストが失敗していたのでワークフローを更新しました
- ci: remove older versions from matrix
- ci: upgrade node.js version

maintenance workflows

---

ameba-color-palette.css

fix: x icon color

---

ameba-color-palette.css

Reverts openameba/ameba-color-palette.css#100
変数名を削除する形で、破壊的な変更になるので一度revertします。

Revert "fix: x icon color"

---

package-lock.json
package.json

chore(release): publish

---

.github/workflows/release.yml
.github/workflows/test.yml

派生ブランチはデフォルトブランチのキャッシュしか活用できないはずなのでそのようにしました

ci: save cache if default branch

---

.renovaterc.json

- アサインでなくレビュワーに変えました
- レビュアーをSpindleチームにしました
- ロックファイルをメンテするようにしました
- アクションのタグをハッシュで指定するようにしました

chore: update renovate settings

---

.renovaterc.json

openameba/renovate-config を使うようにしました

chore: migrate renovate config

---

ameba-color-palette.css

ボタンをホバーしたときの色が定義されていなかったため、追加しました。

feat(spindle-tokens): add hover-button colors

---

.stylelintrc.json
package-lock.json

- **chore: add color-function-alias-notation**
- **chore: update package-lock.json version**
ref: https://github.com/openameba/ameba-color-palette.css/actions/runs/14562025733/job/40846515569#step:7:11

fix: stylelint error

---

ameba-color-palette.css

[feat(spindle-tokens): update design tokens](https://github.com/openameba/spindle/pull/1313)
Spindle TokensにRating用の色を追加したのでそれをameba-color-palette側に反映しました。

Rating用の色を追加
